"use strict";
const $=id=>document.getElementById(id),reduced=matchMedia('(prefers-reduced-motion: reduce)'),audio=$('music');
const memories=[
 [3,'Los abrazos que abrigan','Hay personas que hacen de cualquier lugar un hogar.','Elvita acompañada por dos personas en una celebración'],
 [4,'Pequeñas grandes alegrías','La felicidad suele esconderse en los instantes más sencillos.','Elvita con dos niñas en una celebración'],
 [8,'Sonrisas para guardar','Algunos momentos se quedan con nosotros mucho después de la fotografía.','Elvita junto a una niña con medallas'],
 [5,'Cerca del corazón','Hay compañías que hacen más cálido el camino.','Elvita junto a otra mujer, ambas sonriendo'],
 [6,'La dicha de compartir','Los mejores recuerdos siempre tienen espacio para alguien más.','Elvita acompañada en una fotografía de recuerdo'],
 [7,'Encuentros que iluminan','Entre conversaciones y risas, la vida nos regala sus mejores detalles.','Elvita con una acompañante junto a una pared de ladrillo'],
 [2,'Ser, soñar, sonreír','Agradecer lo vivido y seguir mirando hacia adelante con ilusión.','Elvita sonriendo frente a un espejo'],
 [1,'Un nuevo capítulo','Hoy celebro mi historia y todo lo bonito que aún está por llegar.','Elvita con vestido naranja y globos de cumpleaños']
];
memories.forEach(([photo,title,quote,alt],i)=>{const article=document.createElement('article');article.className='memory reveal';const button=document.createElement('button');button.className='polaroid';button.setAttribute('aria-label','Ampliar recuerdo: '+title);const img=new Image();img.src=`foto-${String(photo).padStart(2,'0')}.webp`;img.alt=alt;img.loading='lazy';const hint=document.createElement('span');hint.textContent='VER RECUERDO ↗';button.append(img,hint);button.onclick=()=>openPhoto(i);const chapter=document.createElement('p');chapter.className='chapter';chapter.textContent=`RECUERDO ${String(i+1).padStart(2,'0')}`;const h=document.createElement('h3');h.textContent=title;const p=document.createElement('p');p.textContent=quote;article.append(button,chapter,h,p);$('timeline').append(article)});
let photoIndex=0;
function showPhoto(){const [photo,title,,alt]=memories[photoIndex];$('large-photo').src=`foto-${String(photo).padStart(2,'0')}.webp`;$('large-photo').alt=alt;$('photo-caption').textContent=title;$('photo-count').textContent=`${photoIndex+1} de ${memories.length}`;$('photo-prev').disabled=photoIndex===0;$('photo-next').disabled=photoIndex===memories.length-1}
function openPhoto(i){photoIndex=i;showPhoto();$('lightbox').showModal();document.body.style.overflow='hidden'}
$('close-photo').onclick=()=>$('lightbox').close();$('lightbox').addEventListener('close',()=>document.body.style.overflow='');$('lightbox').addEventListener('click',e=>{if(e.target===$('lightbox')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});
$('photo-prev').onclick=()=>{if(photoIndex>0){photoIndex--;showPhoto()}};$('photo-next').onclick=()=>{if(photoIndex<7){photoIndex++;showPhoto()}};$('lightbox').addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();$('photo-prev').click()}if(e.key==='ArrowRight'){e.preventDefault();$('photo-next').click()}});
function syncMusic(){$('music-button').textContent=audio.paused?'♫':'Ⅱ';$('music-button').setAttribute('aria-label',audio.paused?'Reproducir música':'Pausar música');$('music-button').setAttribute('aria-pressed',String(!audio.paused))}audio.addEventListener('play',syncMusic);audio.addEventListener('pause',syncMusic);$('music-button').onclick=()=>audio.paused?audio.play().catch(syncMusic):audio.pause();
$('open').onclick=()=>{$('open').disabled=true;$('cover').classList.add('opening');audio.volume=.55;audio.play().catch(syncMusic);setTimeout(()=>{$('cover').hidden=true;$('content').hidden=false;$('music-button').hidden=false;scrollTo(0,0);document.querySelector('.hero h1').focus({preventScroll:true});if(!reduced.matches&&'IntersectionObserver'in window){const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>{el.classList.add('waiting');obs.observe(el)})}},reduced.matches?0:1450)};
for(let i=0;i<34;i++){const day=i-2,el=document.createElement('span');if(day>0){el.textContent=day;if(day===24){el.className='selected';el.setAttribute('aria-label','24 de octubre, fecha de ejemplo')}}$('calendar').append(el)}
const target=Date.parse('2026-10-24T17:00:00-04:00');function tick(){const seconds=Math.max(0,Math.floor((target-Date.now())/1000));[Math.floor(seconds/86400),Math.floor(seconds/3600)%24,Math.floor(seconds/60)%60,seconds%60].forEach((n,i)=>$(['days','hours','minutes','seconds'][i]).textContent=String(n).padStart(2,'0'))}tick();setInterval(tick,1000);
const wa=text=>'https://wa.me/59167408598?text='+encodeURIComponent(text);$('confirm').href=wa('Hola, quisiera confirmar mi asistencia al cumpleaños de Elvita.\nMi nombre: \nNúmero de asistentes: \n¿Me confirman la fecha y la dirección definitivas?');$('questions').href=wa('Hola, tengo una consulta sobre el cumpleaños de Elvita.');$('location').href=wa('Hola, ¿pueden compartirme la ubicación exacta del cumpleaños de Elvita?');
for(let i=0;i<18;i++){const leaf=document.createElement('i');leaf.style.cssText=`--x:${i*43%100}%;--size:${10+i%5*3}px;--duration:${18+i%7*3}s;--delay:${-i*3.2}s`;$('leaves').append(leaf)}
let scheduled=false;addEventListener('scroll',()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{const total=document.documentElement.scrollHeight-innerHeight;$('reading-progress').style.width=(total>0?Math.min(100,scrollY/total*100):0)+'%';scheduled=false})},{passive:true});document.addEventListener('visibilitychange',()=>document.querySelectorAll('#leaves i').forEach(el=>el.style.animationPlayState=document.hidden?'paused':'running'));
